{
    'name': 'Informe de pagos masivos',
    'version': '1.0',
    'description': 'Registra los pagos a realizar de manera centralizada.',
    'summary': 'Seleccione y realice pagos masivos a través de un informe, todo las transaccions a pagar de manera centralizada.',
    'author': 'Toh Soluciones Digitales',
    'website': "https://www.tohsoluciones.com",
    'license': 'LGPL-3',
    'depends': [
        'base',
        'account',
        'account_accountant',
        'purchase',
        'hr_expense',
        'l10n_mx',
        'sign'
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/mail_activity_type_data.xml',
        'data/report_paperformat_data.xml',
        'report/mass_payment_report.xml',
        'report/mass_payment_template.xml',
        'views/account_payment_report_views.xml',
        'wizard/note_history_wizard_views.xml',
        'wizard/transaction_comment_wizard.xml',
        'views/res_users_views.xml',
    ],
    'application': True,
}